import type { Metadata } from "next";
import { Inter, Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";
import ButtonScrollToTop from "@/components/ui/buttonScrollToTop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  weight: ["300", "400", "600"],
  variable: "--font-inter",
});

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ["300", "400", "700"],
  variable: "--font-noto-sans-jp",
});

const RootLayout = (
  { children }: { children: React.ReactNode }
) => {
  return (
    <html lang="en">
      <body
        className={cn(notoSansJP.variable, inter.variable, "antialiased flex flex-col min-h-screen font-notoSansJP")}
      >
        <Navigation />
        <main className="flex-1">
          {children}
        </main>
        <ButtonScrollToTop />
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;